### ISSUE TITLE
🎯 | B4-M1: IPC deployed on Spacenet

### ISSUE THREAD

**Issue by jsoares** [protocol/ConsensusLab#185]
**For work tracking purposes.**

Refer to the parent project issue for high-level discussion and resources.

eta: 2023-04-20

## Blockchain Instance
- [x] consensus-shipyard/lotus#31
- [x] consensus-shipyard/lotus#34
- [x] https://github.com/consensus-shipyard/lotus/issues/21
- [x] https://github.com/consensus-shipyard/lotus/issues/104

## IPC Agent
- [x] consensus-shipyard/lotus#35
- [x] consensus-shipyard/lotus#36
- [x] consensus-shipyard/lotus#38
- [x] consensus-shipyard/ipc-agent#15
- [x] https://github.com/consensus-shipyard/ipc-agent/issues/18
- [x] https://github.com/consensus-shipyard/ipc-agent/issues/17
- [x] consensus-shipyard/ipc-agent#16

## Actors
- [x] consensus-shipyard/ipc-gateway#18

## Checkpointing
- [x]  https://github.com/consensus-shipyard/ipc-agent/issues/14

## IPLD Resolver
- [x] https://github.com/consensus-shipyard/ipc-agent/issues/39

## Testing
- [x] https://github.com/consensus-shipyard/ipc-agent/issues/92
- [ ] https://github.com/consensus-shipyard/ipc-agent/issues/91

## Cross-net messages
- [x] https://github.com/consensus-shipyard/ipc-agent/issues/19
- [x] https://github.com/consensus-shipyard/ipc-agent/issues/94
- [ ] https://github.com/consensus-shipyard/ipc-agent/issues/96
- [ ] https://github.com/consensus-shipyard/ipc-agent/issues/72
- [x] consensus-shipyard/ipc-agent#13

## Deployment
- [x] https://github.com/consensus-shipyard/spacenet/issues/21
- [x] https://github.com/consensus-shipyard/ipc-agent/issues/20
- [ ] https://github.com/consensus-shipyard/spacenet/issues/25
- [ ] https://github.com/consensus-shipyard/IPC-design-reference-spec/issues/4

## Internal audit
- [x] Populate all READMEs.
- [x] Review the code structure and architecture
- [ ] Review the documentation, design and architecture diagrams
- [ ] Evaluate the code’s quality, compliance, and security
- [x] Reduce boilerplate code and increase readability by updating critical code to use Andrey's codegen

## Architecture

![image](https://user-images.githubusercontent.com/6717133/206700087-bafa10cc-bbd1-4db3-b945-f59c348dfffe.png)

**Comment by momack2** [comment]
@jsoares is this technically completed now?

**Comment by jsoares** [comment]
@momack2 We extended the milestone to 20 April as it encompasses all the launch tasks related to M1. We expect to freeze the implementation by EOW (14 Apr) and leave a few days for final testing, implementation, and network reset next week.

**Comment by momack2** [comment]
ack - seems like it should be marked complete now though, right?

**Comment by jsoares** [comment]
It should, mea culpa. thanks for the call out!
