### ISSUE TITLE
Finalizer Component (Granite) for Filecoin

### ISSUE THREAD

**Issue by ranchalp** [protocol/ConsensusLab#214]
Description: The Finalizer Component (FC) brings fast finality to Filecoin via a dedicated component that executes a BFT consensus protocol (Granite)  to finalize Filecoin tipsets. 

ETA: 2024-03-31
Maintainer: @ranchalp

```[tasklist]
### Milestones
- [ ] Get community-wide agreement on requirements and assumptions (censorship resistance, adversary, latency, safety, liveness, network, resistance to eclipse attacks). Core devs, CL and CNL should be part of this discussion at least.
- [ ] Settle on design given community-wide agreement on requirements and assumptions
- [ ] Prototyping and testing to select system parameters
- [ ] Auditing and calibration testnet
- [ ] Mainnet release
```

Known dependencies:
- None (but other projects should depend on this).
