### ISSUE TITLE
Calculate EC's finality

### ISSUE THREAD

**Issue by guy-goren** [protocol/ConsensusLab#215]
Description: Calculate EC's error probabilities based on observed history

ETA: 2023-12-25
Maintainer: Guy

```[tasklist]
### Milestones
- [ ] Write document that describes the theory and is readable to humans
- [ ] Confer with probability experts
- [ ] Write program to calculate probabilities based on the theoretical analysis
```

Known dependencies:
- None

View this [starmap](https://starmap.site/) at: <link>
