### ISSUE TITLE
Faster block time in mainnet GA

### ISSUE THREAD

**Issue by ranchalp** [protocol/ConsensusLab#216]
Description:  Optimize network layer, consensus step, PoSts, etc. in order to reduce epoch time and provide faster block time. 

ETA: 2024-12-31
Maintainer: @ranchalp

```[tasklist]
### Milestones
- [ ] Explore optimization opportunities across stack
- [ ] Consider optimizations in network and dissemination layer (Byzantine broadcast, Narwhal-like, etc.)
- [ ] Come up with proposal
- [ ] Settle on requirements and assumptions
- [ ] Propose design
- [ ] Prototype and test
- [ ] Mainnet release
```

Known dependencies:
- None
