### ISSUE TITLE
Bridging: proofs of finality (and of state transitions for power table)

### ISSUE THREAD

**Issue by ranchalp** [protocol/ConsensusLab#217]
Description: Implement a bridging solution from Filecoin into other chains given the faster finality and BFT-like quorum signatures derived from the Finalizer Component.

ETA: 2024-12-31
Maintainer: @ranchalp

```[tasklist]
### Milestones
- [ ]  SNARKs and others, SOTA scoping
- [ ] Settle on design
- [ ] Prototype and testing
- [ ] Mainnet release
```

Known dependencies:
- #214
